languageCode = "ta"
languageName = "Tamil"
languageDirection = "ltr"
weight = 1

title = "kbdharun"
copyright = "Copyright kbdharun 2024-present"

[params]
dateFormat = "2 January 2006"

# mainSections = ["section1", "section2"]
#description = "My awesome website"

[params.author]
 name = "Dharun Krishna K B"
 image = "profile.webp"
 headline = "Developer, Writer, Open-source Enthusiast, CS Undergrad."
 bio = "Developer, Writer, Open-source Enthusiast, CS Undergrad."
 links = [
    { email = "mailto:mail@kbdharun.dev" },
    { link = "https://blog.kbdharun.dev/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/kbdharun" },
     { gitlab = "https://gitlab.com/kbdharun" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
     { hashnode = "https://hashnode.com/@kbdk" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://www.linkedin.com/in/kbdk/" },
     { mastodon = "https://mastodon.social/@kbdharunkrishna" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
    { reddit = "https://www.reddit.com/user/iKbdkblogs" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
    { stack-overflow = "https://stackoverflow.com/users/15733296/k-b-dharun-krishna" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/kbdharun" },
  #   { youtube = "https://youtube.com/username" },
  ]
