# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  url = "https://blog.kbdharun.dev"
  weight = 10

[[main]]
  name = "Works"
  pageRef = "/works"
  weight = 20

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Blog"
   pageRef = "/contributions"
   weight = 20

 [[footer]]
   name = "CV"
   pageRef = "/cv"
   weight =30
 
 [[footer]]
   name = "Contributions"
   pageRef = "/contributions"
   weight = 40

 [[footer]]
   name = "Localization"
   pageRef = "/localization"
   weight = 50

 [[footer]]
   name = "Projects"
   pageRef = "/projects"
   weight = 60
